### ISSUE TITLE
Cannot select word in chrome browser url bar by direction key

### ISSUE THREAD

**Issue by leisureshadow** [openvanilla/McBopomofo#145] opened 2019-06-15 06:42 UTC
I found that I cannot select word when I type word in chrome browser url bar.
Reproduce steps:
1. key some chinese word into the chrome url bar
2. press down key to open the candidates
3. press down to select the candidate

At the step 3, chrome would select the next url recommendation rather than choosing the next candidate for me.

My chrome version: Version 74.0.3729.169 (Official Build) (64-bit)
McBopomofo version: Version 0.9.10 (805)

**Comment by lukhnos** [comment] 2019-06-16 03:58
I can reproduce this bug with McBopomofo. I observed that when an arrow key is pressed, the current buffer gets committed. McBopomofo must have exited the candidate-selection state at that point.

Interestingly, Chrome also has issues with built-in input methods (I tried both Apple's Zhuyin and Apple's Japanese IME): when I pressed the down key, Chrome still moved the URL selection to the next suggestion. Apple's built-in input methods, though, did *not* exit the candidate-selection state. Therefore it was still possible to choose the right candidate. I'm not sure how Chrome behaved before this though, but it seems the current version of Chrome is over-eager with an input method's buffer is still active (i.e. not empty).

Also interestingly, OpenVanilla behaves like Apple's built-in input methods, *not* McBopomofo. I haven't looked at the code for a long time, but I have to guess it has to do with OV's handling with forced commit events. Perhaps OV does not exit candidate-selection state if the commit event is not from the user.

Based on all this, I encourage anyone who runs into this to file a bug with Chrome, since Apple's own built-in input methods are also affected, and the symptom is what I just described above: Chrome's URL bar is over-eager when an input method still has an active, non-empty composing (edit) buffer.

It'd also be great if someone can help verify if this is a regression on Chrome's part.

**Comment by ShikiSuen** [comment] 2019-06-18 05:45
This bug also exists in Microsoft Edge Chromium. McBopomofo is not the only one which gets troubled with this bug, but also Yahoo KeyKey.

**Comment by ShikiSuen** [comment] 2019-06-18 05:47
@lukhnos Which version of macOS are you using? I tested the macOS Mojave 10.14.5 built-in Japanese IME together with Google Chrome Dev 77.0.3824.6 and I found that this bug is not triggered.

**Comment by leisureshadow** [comment] 2019-07-11 06:18
Thx @lukhnos .
After I installed the newest version directly from this repo, the problem is fixed.

**Closed as completed** 2021-11-11 17:29 UTC
